/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace google {
    export namespace protobuf {
        export interface FileDescriptorSet {
            file?: protobuf.FileDescriptorProto[];
        }
        export interface FileDescriptorProto {
            name?: string;
            package?: string;
            dependency?: string[];
            public_dependency?: number[];
            weak_dependency?: number[];
            message_type?: protobuf.DescriptorProto[];
            enum_type?: protobuf.EnumDescriptorProto[];
            service?: protobuf.ServiceDescriptorProto[];
            extension?: protobuf.FieldDescriptorProto[];
            options?: protobuf.FileOptions;
            source_code_info?: protobuf.SourceCodeInfo;
            syntax?: string;
        }
        export interface DescriptorProto {
            name?: string;
            field?: protobuf.FieldDescriptorProto[];
            extension?: protobuf.FieldDescriptorProto[];
            nested_type?: protobuf.DescriptorProto[];
            enum_type?: protobuf.EnumDescriptorProto[];
            extension_range?: DescriptorProto.ExtensionRange[];
            oneof_decl?: protobuf.OneofDescriptorProto[];
            options?: protobuf.MessageOptions;
            reserved_range?: DescriptorProto.ReservedRange[];
            reserved_name?: string[];
        }
        export namespace DescriptorProto {
            export interface ExtensionRange {
                start?: number;
                end?: number;
            }
            export interface ReservedRange {
                start?: number;
                end?: number;
            }
        }
        export interface FieldDescriptorProto {
            name?: string;
            number?: number;
            label?: FieldDescriptorProto.Label;
            type?: FieldDescriptorProto.Type;
            type_name?: string;
            extendee?: string;
            default_value?: string;
            oneof_index?: number;
            json_name?: string;
            options?: protobuf.FieldOptions;
        }
        export namespace FieldDescriptorProto {
            export enum Type {
                TYPE_DOUBLE = 1,
                TYPE_FLOAT = 2,
                TYPE_INT64 = 3,
                TYPE_UINT64 = 4,
                TYPE_INT32 = 5,
                TYPE_FIXED64 = 6,
                TYPE_FIXED32 = 7,
                TYPE_BOOL = 8,
                TYPE_STRING = 9,
                TYPE_GROUP = 10,
                TYPE_MESSAGE = 11,
                TYPE_BYTES = 12,
                TYPE_UINT32 = 13,
                TYPE_ENUM = 14,
                TYPE_SFIXED32 = 15,
                TYPE_SFIXED64 = 16,
                TYPE_SINT32 = 17,
                TYPE_SINT64 = 18,
            }
            export enum Label {
                LABEL_OPTIONAL = 1,
                LABEL_REQUIRED = 2,
                LABEL_REPEATED = 3,
            }
        }
        export interface OneofDescriptorProto {
            name?: string;
            options?: protobuf.OneofOptions;
        }
        export interface EnumDescriptorProto {
            name?: string;
            value?: protobuf.EnumValueDescriptorProto[];
            options?: protobuf.EnumOptions;
        }
        export interface EnumValueDescriptorProto {
            name?: string;
            number?: number;
            options?: protobuf.EnumValueOptions;
        }
        export interface ServiceDescriptorProto {
            name?: string;
            method?: protobuf.MethodDescriptorProto[];
            options?: protobuf.ServiceOptions;
        }
        export interface MethodDescriptorProto {
            name?: string;
            input_type?: string;
            output_type?: string;
            options?: protobuf.MethodOptions;
            client_streaming?: boolean;
            server_streaming?: boolean;
        }
        export interface FileOptions {
            java_package?: string;
            java_outer_classname?: string;
            java_multiple_files?: boolean;
            java_generate_equals_and_hash?: boolean;
            java_string_check_utf8?: boolean;
            optimize_for?: FileOptions.OptimizeMode;
            go_package?: string;
            cc_generic_services?: boolean;
            java_generic_services?: boolean;
            py_generic_services?: boolean;
            deprecated?: boolean;
            cc_enable_arenas?: boolean;
            objc_class_prefix?: string;
            csharp_namespace?: string;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export namespace FileOptions {
            export enum OptimizeMode {
                SPEED = 1,
                CODE_SIZE = 2,
                LITE_RUNTIME = 3,
            }
        }
        export interface MessageOptions {
            message_set_wire_format?: boolean;
            no_standard_descriptor_accessor?: boolean;
            deprecated?: boolean;
            map_entry?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface FieldOptions {
            ctype?: FieldOptions.CType;
            packed?: boolean;
            jstype?: FieldOptions.JSType;
            lazy?: boolean;
            deprecated?: boolean;
            weak?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export namespace FieldOptions {
            export enum CType {
                STRING = 0,
                CORD = 1,
                STRING_PIECE = 2,
            }
            export enum JSType {
                JS_NORMAL = 0,
                JS_STRING = 1,
                JS_NUMBER = 2,
            }
        }
        export interface OneofOptions {
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface EnumOptions {
            allow_alias?: boolean;
            deprecated?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface EnumValueOptions {
            deprecated?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface ServiceOptions {
            deprecated?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface MethodOptions {
            deprecated?: boolean;
            uninterpreted_option?: protobuf.UninterpretedOption[];
        }
        export interface UninterpretedOption {
            name?: UninterpretedOption.NamePart[];
            identifier_value?: string;
            positive_int_value?: number;
            negative_int_value?: number;
            double_value?: number;
            string_value?: Uint8Array;
            aggregate_value?: string;
        }
        export namespace UninterpretedOption {
            export interface NamePart {
                name_part?: string;
                is_extension?: boolean;
            }
        }
        export interface SourceCodeInfo {
            location?: SourceCodeInfo.Location[];
        }
        export namespace SourceCodeInfo {
            export interface Location {
                path?: number[];
                span?: number[];
                leading_comments?: string;
                trailing_comments?: string;
                leading_detached_comments?: string[];
            }
        }
        export interface GeneratedCodeInfo {
            annotation?: GeneratedCodeInfo.Annotation[];
        }
        export namespace GeneratedCodeInfo {
            export interface Annotation {
                path?: number[];
                source_file?: string;
                begin?: number;
                end?: number;
            }
        }
    }
}

